# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Sep 05 23:44:29 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 673)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 872, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_3.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lc_treeview = LCTreeView(self.tab)
        self.lc_treeview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lc_treeview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lc_treeview.setDragEnabled(True)
        self.lc_treeview.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lc_treeview.setHeaderHidden(True)
        self.lc_treeview.setObjectName("lc_treeview")
        self.horizontalLayout.addWidget(self.lc_treeview)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeView = QtGui.QTreeView(self.tab_2)
        self.treeView.setMouseTracking(True)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setHeaderHidden(True)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_2.addWidget(self.treeView)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionGenerate_HRUs_from_selected = QtGui.QAction(MainWindow)
        self.actionGenerate_HRUs_from_selected.setObjectName("actionGenerate_HRUs_from_selected")
        self.actionPrimary = QtGui.QAction(MainWindow)
        self.actionPrimary.setObjectName("actionPrimary")
        self.actionSecondary = QtGui.QAction(MainWindow)
        self.actionSecondary.setEnabled(False)
        self.actionSecondary.setObjectName("actionSecondary")
        self.actionGenerate_HRUs = QtGui.QAction(MainWindow)
        self.actionGenerate_HRUs.setObjectName("actionGenerate_HRUs")
        self.actionImport_file = QtGui.QAction(MainWindow)
        self.actionImport_file.setObjectName("actionImport_file")
        self.actionHRU_paramaters = QtGui.QAction(MainWindow)
        self.actionHRU_paramaters.setObjectName("actionHRU_paramaters")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionHRU_raster = QtGui.QAction(MainWindow)
        self.actionHRU_raster.setObjectName("actionHRU_raster")
        self.actionHRU_parameters = QtGui.QAction(MainWindow)
        self.actionHRU_parameters.setObjectName("actionHRU_parameters")
        self.menuSave.addAction(self.actionHRU_raster)
        self.menuSave.addAction(self.actionHRU_parameters)
        self.menuFile.addAction(self.actionImport_file)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuTools.addAction(self.actionGenerate_HRUs)
        self.menuView.addAction(self.actionHRU_paramaters)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Basin", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_HRUs_from_selected.setText(QtGui.QApplication.translate("MainWindow", "Generate HRUs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrimary.setText(QtGui.QApplication.translate("MainWindow", "Primary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSecondary.setText(QtGui.QApplication.translate("MainWindow", "Secondary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_HRUs.setText(QtGui.QApplication.translate("MainWindow", "Generate HRUs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_file.setText(QtGui.QApplication.translate("MainWindow", "Import file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHRU_paramaters.setText(QtGui.QApplication.translate("MainWindow", "HRU paramaters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHRU_raster.setText(QtGui.QApplication.translate("MainWindow", "HRU raster", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHRU_parameters.setText(QtGui.QApplication.translate("MainWindow", "HRU parameters", None, QtGui.QApplication.UnicodeUTF8))

from lctreeview import LCTreeView
